[dns_server]
ansible-controller  eth0_ip=                  eth0_mac=                     eth1_ip=192.168.100.254                 eth1_mac=08:00:27:FF:FF:A2    ansible_host=192.168.100.254    ansibleport=22 

[hosts]
ubuntu-1            eth0_ip=                  eth0_mac=                     eth1_ip=192.168.100.10                  eth1_mac=08:00:27:FF:FF:A2    ansible_host=192.168.100.10   ansible_port=22
ubuntu-2            eth0_ip=                  eth0_mac=                     eth1_ip=192.168.100.20                  eth1_mac=08:00:27:FF:FF:A3    ansible_host=192.168.100.20   ansible_port=22    
